### ISSUE TITLE
How to use this with other coins?

### ISSUE THREAD

**Issue by tuxlee** [TheZ3ro/bitcoin-privatekey-db#9]
deleted

**Comment by TheZ3ro** [comment]
Right now this project use an old version of [pycoin](https://github.com/richardkiss/pycoin)'s **Key** class https://github.com/TheZ3ro/bitcoin-privatekey-db/blob/master/server.py#L22-L27

I see now that the latest version of pycoin supports a lot of alt-coins: https://github.com/richardkiss/pycoin/tree/main/pycoin/symbols

A sample of code to make the `secret_to_address` function work with multiple coins could be:
```python
from pycoin.networks.registry import network_for_netcode

def secret_to_address(secret_exponent, coin="BTC"):
    network = network_for_netcode(coin)
    k = network.keys.private(secret_exponent=secret_exponent)
    addr = k.address(use_uncompressed=True)
    caddr = k.address()
    wif = k.wif(use_uncompressed=True)
    return secret_exponent, wif, addr, caddr
```

from there you can call `secret_to_address` with a different `coin` parameter in order to use it for example
```python
secret_to_address(1, coin="DOGE")
```

**Comment by Globeyxyz** [comment]
Hey thanks! When i am back on my terminal I'll give this a run. Also been thinking about trying this with Django and then adding search somehow to show the page number the keys are on etc. I'll keep posted.
